server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

token:
  access-expired-time: 300000
  refresh-expired-time: 7000000
  secret: token_key

spring:
  application:
    name: apigateway-service
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowCredentials: true
            allowedHeaders:
              - x-requested-with
              - authorization
              - content-type
              - credential
              - X-AUTH-TOKEN
              - X-CSRF-TOKEN
            allowedMethods:
              - POST
              - GET
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway Global Filter
            preLogger: true
            postLogger: true
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/login
            - Method=POST,OPTIONS
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/logout
            - Method=POST,OPTIONS
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/users
            - Method=POST,OPTIONS
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/token/**
            - Method=GET,OPTIONS
          filters:
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/users/email
            - Method=GET,OPTIONS
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/users/id
            - Method=GET,OPTIONS
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/users/**
            - Method=GET,PUT,OPTIONS
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/users/all
            - Method=GET,OPTIONS
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter
            - RoleFilter

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/users
            - Method=DELETE,GET,OPTIONS
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/status
            - Method=GET,OPTIONS
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}

        - id: join-service
          uri: lb://JOIN-SERVICE
          predicates:
            - Path=/join-service/join
            - Method=POST,OPTIONS
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/join-service/(?<segment>.*), /$\{segment}

        - id: join-service
          uri: lb://JOIN-SERVICE
          predicates:
            - Path=/join-service/leave
            - Method=DELETE,OPTIONS
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/join-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter

        - id: user-manage-service
          uri: lb://USER-MANAGE-SERVICE
          predicates:
            - Path=/user-manage-service/**
            - Method=GET,OPTIONS
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-manage-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter

        - id: group-service
          uri: lb://GROUP-SERVICE
          predicates:
            - Path=/group-service/**
            - Method=GET,POST,DELETE,OPTIONS
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/group-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter
